# path: /home/netto/.bashrc

HISTSIZE=9999
HISTFILESIZE=9999

echo a_password | sudo -S sh -c 'echo 1024 > /sys/module/usbcore/parameters/usbfs_memory_mb'
# check with cpufreq-info
echo a_password | sudo -S sh -c 'cpupower frequency-set -u 1200000'

export PATH=/home/a_user/apps/bin:$PATH
export MAKEFLAGS=-j$(($(nproc)-1))
export mesa_glthread=true
